// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM-3FPL8BjGKVSVAgYTZThQLrLJFjT4dQ',
    appId: '1:129973478215:web:72f2fb0b5865ceea09a262',
    messagingSenderId: '129973478215',
    projectId: 'twitter-clone-fc7a7',
    authDomain: 'twitter-clone-fc7a7.firebaseapp.com',
    storageBucket: 'twitter-clone-fc7a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHm3PRyo-PdORhoK3Kz6E2eD_TbKGJfY',
    appId: '1:129973478215:android:a963c7dc5d684e8709a262',
    messagingSenderId: '129973478215',
    projectId: 'twitter-clone-fc7a7',
    storageBucket: 'twitter-clone-fc7a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxStvYuLQp_WGEH_yGuRGKpMSneWyxofY',
    appId: '1:129973478215:ios:bdecf5a78ceedf9509a262',
    messagingSenderId: '129973478215',
    projectId: 'twitter-clone-fc7a7',
    storageBucket: 'twitter-clone-fc7a7.appspot.com',
    iosBundleId: 'com.example.twitterCloneWithBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxStvYuLQp_WGEH_yGuRGKpMSneWyxofY',
    appId: '1:129973478215:ios:9f0915890441c0ce09a262',
    messagingSenderId: '129973478215',
    projectId: 'twitter-clone-fc7a7',
    storageBucket: 'twitter-clone-fc7a7.appspot.com',
    iosBundleId: 'com.example.twitterCloneWithBloc.RunnerTests',
  );
}
